server:
  port: 7778

dubbo:
  application:
    name: boot-provider2
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20881
  scan:
      base-packages: com.hcy.springbootdubboprovider.service
  provider:
    group: test