server:
  port: 7779

dubbo:
  application:
    name: boot-consumer
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20881
#  scan:
#      base-packages: com.hcy.springbootdubboprovider.service
  consumer:
    group: test