server:
  port: 7777

dubbo:
  application:
    name: boot-provider1
  registry:
    address: zookeeper://localhost:2181
  protocol:
    name: dubbo
    port: 20880
  scan:
    base-packages: com.hcy.springbootdubboprovider.service.impl
  provider:
    group: test



